"""Test report generation — JSON + Markdown output.

Aggregates results from navigation runs and regression checks
into machine-readable and human-readable reports.
"""

import json
from datetime import datetime, timezone
from pathlib import Path

from navigator import UseCaseResult


def generate_json_report(
    results: list[UseCaseResult],
    output_path: str | Path,
) -> Path:
    """Generate JSON report from use case results."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    report = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "summary": {
            "total_use_cases": len(results),
            "passed": sum(1 for r in results if r.success),
            "failed": sum(1 for r in results if not r.success),
            "total_steps": sum(len(r.steps) for r in results),
            "total_duration_ms": sum(r.duration_ms for r in results),
        },
        "use_cases": [r.to_dict() for r in results],
    }

    path.write_text(json.dumps(report, indent=2), encoding="utf-8")
    return path


def generate_markdown_report(
    results: list[UseCaseResult],
    output_path: str | Path,
) -> Path:
    """Generate human-readable Markdown report."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Visual QA Report",
        f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        "",
        "## Summary",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Use Cases | {len(results)} |",
        f"| Passed | {sum(1 for r in results if r.success)} |",
        f"| Failed | {sum(1 for r in results if not r.success)} |",
        f"| Total Steps | {sum(len(r.steps) for r in results)} |",
        f"| Total Duration | {sum(r.duration_ms for r in results) / 1000:.1f}s |",
        "",
    ]

    for uc in results:
        status = "PASS" if uc.success else "FAIL"
        lines.extend([
            f"## {uc.name} — {status}",
            "",
        ])
        if uc.error:
            lines.append(f"> **Error:** {uc.error}")
            lines.append("")

        lines.extend([
            "| # | Screen | Action | Status | Duration |",
            "|---|--------|--------|--------|----------|",
        ])
        for i, step in enumerate(uc.steps, 1):
            s_status = "pass" if step.success else "**FAIL**"
            action_desc = step.action.description if step.action else "—"
            lines.append(
                f"| {i} | {step.screen.name} | {action_desc} | {s_status} | {step.duration_ms}ms |"
            )

        lines.append("")

        # List failures
        failures = [s for s in uc.steps if not s.success]
        if failures:
            lines.append("### Failures")
            lines.append("")
            for f in failures:
                lines.append(f"- **{f.screen.name}**: {f.error}")
                if f.screenshot_path and not f.screenshot_path.startswith("ERROR"):
                    lines.append(f"  - Screenshot: `{f.screenshot_path}`")
                if f.xml_path and not f.xml_path.startswith("ERROR"):
                    lines.append(f"  - UI dump: `{f.xml_path}`")
            lines.append("")

    # Footer
    lines.extend([
        "---",
        "*Generated by visual-qa automation*",
    ])

    path.write_text("\n".join(lines), encoding="utf-8")
    return path
