version: '3.8'

services:
  yarp:
    build:
      context: ./dejting-yarp
      dockerfile: Dockerfile
    ports:
      - "5177:80"
    depends_on:
      - auth-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "5000:80" # 5000:80 ?? 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Set the root password for MySQL
      MYSQL_DATABASE: AuthServiceDb  # Set the name of the initial database
      MYSQL_USER: authuser  # Set the name of a non-root user
      MYSQL_PASSWORD: authpassword  # Set the password for the non-root user
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:


  # Uncomment and configure these services when they are ready
  # user-service:
  #   image: your-user-service-image
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development

  # match-service:
  #   image: your-match-service-image
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development