#!/bin/bash
# ═══════════════════════════════════════════════════════════════
# AI Context Generator
# Injects live system state DIRECTLY into .github/copilot-instructions.md
# between <!-- LIVE-CONTEXT-START --> and <!-- LIVE-CONTEXT-END --> markers.
#
# This is the ONLY file Copilot auto-loads every conversation.
# Everything the AI needs goes here — no separate files to read.
#
# Usage: bash scripts/generate-ai-context.sh
# Auto-runs on: ./dev-start.sh
# ═══════════════════════════════════════════════════════════════

set -euo pipefail
ROOT="/home/m/development/DatingApp"
FLUTTER_ROOT="/home/m/development/mobile-apps/flutter/dejtingapp"
TARGET="$ROOT/.github/copilot-instructions.md"
TMPFILE=$(mktemp)

# Verify sentinel markers exist
if ! grep -q 'LIVE-CONTEXT-START' "$TARGET"; then
    echo "❌ Missing LIVE-CONTEXT-START marker in $TARGET"
    exit 1
fi

echo "🧠 Generating live context..."

# ─── Build the live context section ────────────────────────────
{
cat << 'HEADER'
<!-- LIVE-CONTEXT-START — Auto-generated by scripts/generate-ai-context.sh — DO NOT EDIT BELOW -->
## Live System Context
> Auto-generated. Run `bash scripts/generate-ai-context.sh` to refresh.
HEADER

# ─── Service ports & DBs ──────────────────────────────────────
echo ""
echo "### Services"
echo '| Port | Service | DB |'
echo '|------|---------|-----|'
echo '| 8080 | dejting-yarp (gateway) | - |'
echo '| 8082 | UserService | MySQL :3310 UserServiceDb |'
echo '| 8083 | MatchmakingService | MySQL :3309 MatchmakingDb |'
echo '| 8085 | photo-service | MySQL :3310 PhotoServiceDb |'
echo '| 8086 | messaging-service (SignalR) | MySQL :3310 MessagingServiceDb |'
echo '| 8087 | swipe-service | MySQL :3310 SwipeServiceDb |'
echo '| 8088 | safety-service | - |'
echo '| 8089 | bot-service | SQLite bot-service.db |'
echo '| 8090 | Keycloak | Docker |'

# ─── Health check ──────────────────────────────────────────────
echo ""
echo "### Service Health"
python3 -c "
import urllib.request
services = [
    ('YARP', 8080), ('User', 8082), ('Matchmaking', 8083),
    ('Photo', 8085), ('Messaging', 8086), ('Swipe', 8087),
    ('Safety', 8088), ('Bot', 8089),
]
for name, port in services:
    try:
        r = urllib.request.urlopen(f'http://localhost:{port}/health', timeout=2)
        print(f'- {name} (:{port}): UP')
    except:
        print(f'- {name} (:{port}): DOWN')
try:
    urllib.request.urlopen('http://localhost:8090/realms/DatingApp', timeout=2)
    print('- Keycloak (:8090): UP')
except:
    print('- Keycloak (:8090): DOWN')
" 2>/dev/null || echo "- (health check failed — services may be offline)"

# ─── Keycloak users ───────────────────────────────────────────
echo ""
echo "### Keycloak Users (realm: DatingApp)"
echo "Admin: admin/admin on master realm at localhost:8090"
python3 -c "
import urllib.request, urllib.parse, json
try:
    data = urllib.parse.urlencode({'grant_type':'password','client_id':'admin-cli','username':'admin','password':'admin'}).encode()
    req = urllib.request.Request('http://localhost:8090/realms/master/protocol/openid-connect/token', data=data)
    r = urllib.request.urlopen(req, timeout=5)
    token = json.loads(r.read())['access_token']
    req2 = urllib.request.Request('http://localhost:8090/admin/realms/DatingApp/users?max=50')
    req2.add_header('Authorization', f'Bearer {token}')
    users = json.loads(urllib.request.urlopen(req2, timeout=10).read())
    print('| Username | Keycloak ID | Email |')
    print('|----------|-------------|-------|')
    for u in sorted(users, key=lambda x: x.get('username','')):
        email = u.get('email', '-')
        print(f\"| {u['username']} | \`{u['id']}\` | {email} |\")
except Exception as e:
    print(f'(Keycloak offline: {e})')
" 2>/dev/null || echo "(Keycloak query failed)"

# ─── Bot state ─────────────────────────────────────────────────
echo ""
echo "### Bot State"
BOT_DB="$ROOT/bot-service/BotService/bot-service.db"
if [ -f "$BOT_DB" ]; then
    python3 -c "
import sqlite3, json
db = sqlite3.connect('$BOT_DB')
cur = db.cursor()
cur.execute('SELECT PersonaId, Status, KeycloakUserId, ProfileId, UnresponsiveUsersJson, MessagesSentPerUserJson FROM BotStates')
for row in cur.fetchall():
    unr = json.loads(row[4]) if row[4] else {}
    msgs = json.loads(row[5]) if row[5] else {}
    print(f'- **{row[0]}**: Status={row[1]}, KeycloakId=\`{row[2]}\`, ProfileId={row[3]}, MsgsSent={sum(msgs.values())}')
db.close()
" 2>/dev/null || echo "(bot DB query failed)"
else
    echo "(bot-service.db not found)"
fi

# ─── Flutter key files ─────────────────────────────────────────
echo ""
echo "### Flutter Client"
echo "Root: \`$FLUTTER_ROOT\`"
echo ""
echo "**Screens:** $(ls "$FLUTTER_ROOT/lib/screens/" 2>/dev/null | wc -l) files"
echo '```'
ls "$FLUTTER_ROOT/lib/screens/" 2>/dev/null | sed 's/^/  /'
echo '```'
echo "**Services:** $(ls "$FLUTTER_ROOT/lib/services/" 2>/dev/null | wc -l) files"
echo '```'
ls "$FLUTTER_ROOT/lib/services/" 2>/dev/null | sed 's/^/  /'
echo '```'

# ─── Backend API surface ──────────────────────────────────────
echo ""
echo "### Backend Controllers & Hubs"
for svc in UserService MatchmakingService photo-service messaging-service swipe-service "bot-service/BotService" "safety-service/SafetyService"; do
    svc_path="$ROOT/$svc"
    svc_name=$(basename "$svc")
    if [ -d "$svc_path" ]; then
        controllers=$(ls "$svc_path/Controllers/" 2>/dev/null || true | tr '\n' ', ' | sed 's/,$//')
        hubs=$(ls "$svc_path/Hubs/" 2>/dev/null || true | tr '\n' ', ' | sed 's/,$//')
        line="- **$svc_name**: $controllers"
        [ -n "$hubs" ] && line="$line | Hubs: $hubs"
        echo "$line"
    fi
done

# ─── Known gotchas ─────────────────────────────────────────────
echo ""
echo "### Known Gotchas"
echo "- **SignalR format**: Flutter sends positional args but MessagingHub.Spec expects object. REST fallback \`/api/messages\` works."
echo "- **Dev login identity**: Flutter 'Dev Sign In' uses \`bot_demo-user@bot.local\` / \`bot_pass_demo-user\` → keycloakId \`167d5636-f945-4726-9fd8-fd1d8d9b96c9\` → 'Alex Devsson' → ProfileId 1 across all services. (The old \`demo@example.com\` user was removed — do not reintroduce it.)"
echo "- **Bot demo-user**: Bot-service has a \"demo-user\" bot persona = same identity as the Flutter dev user. If Active, creates rapid message loop. Keep paused."
echo "- **LLM keys**: groq/gemini/ollama circuit-break without API keys. Bots use canned Swedish fallback."
echo "- **Photo auth**: Photos need \`Authorization: Bearer <token>\` header. Use \`AuthenticatedAvatar\` widget. URL: \`http://10.0.2.2:8085/api/photos/{id}/image\`"
echo "- **ConversationId**: REST = alphabetically-sorted keycloak IDs joined by \`_\`. Spec hub = matchId as string."
echo "- **Emulator host**: Use \`10.0.2.2\` for localhost from Android emulator."

# ─── Timestamp ─────────────────────────────────────────────────
echo ""
echo "_Context generated: $(date '+%Y-%m-%d %H:%M:%S')_"

echo "<!-- LIVE-CONTEXT-END -->"
} > "$TMPFILE"

# ─── Inject into copilot-instructions.md ───────────────────────
python3 -c "
import re
with open('$TARGET', 'r') as f:
    content = f.read()
with open('$TMPFILE', 'r') as f:
    replacement = f.read()
pattern = r'<!-- LIVE-CONTEXT-START.*?<!-- LIVE-CONTEXT-END -->'
new_content = re.sub(pattern, replacement.strip(), content, flags=re.DOTALL)
with open('$TARGET', 'w') as f:
    f.write(new_content)
print(f'Injected {len(replacement.splitlines())} lines of live context into .github/copilot-instructions.md')
"

rm -f "$TMPFILE"
echo "✅ Done"
